[workspace]
members = [
    "node",
    "pallets/poa",
    "pallets/poa/rpc",
    "pallets/token_migration",
    "pallets/core_mods",
    "pallets/core_mods/rpc",
    "pallets/staking_rewards",
    "pallets/staking_rewards/rpc",
    "runtime",
]
[profile.release]
panic = "unwind"
